use sentrdel_review::dependency::{
    DependencyError, Ecosystem, LockfileKind, MAX_LOCKFILE_BYTES, OfflineAdvisoryProvider,
    dependency_delta, parse_lockfile,
};

const CARGO_BEFORE: &[u8] = br#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "app"
version = "0.1.0"

[[package]]
name = "safecrate"
version = "1.0.0"
"#;

const CARGO_AFTER: &[u8] = br#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "app"
version = "0.1.0"

[[package]]
name = "safecrate"
version = "1.1.0"

[[package]]
name = "badcrate"
version = "2.0.0"
"#;

const NPM_BEFORE: &[u8] = br#"{
  "name": "fixture",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "fixture", "version": "0.0.0" },
    "node_modules/safe": { "version": "1.0.0" }
  }
}"#;

const NPM_AFTER: &[u8] = br#"{
  "name": "fixture",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "fixture", "version": "0.0.0" },
    "node_modules/safe": { "version": "1.0.0" },
    "node_modules/badpkg": { "version": "1.2.3" },
    "node_modules/@scope/tool": { "version": "4.5.6" }
  }
}"#;

const OFFLINE_ADVISORIES: &[u8] =
    include_bytes!("../../../fixtures/engines/t042-offline-advisories.json");

#[test]
fn cargo_lock_delta_is_deterministic_without_executing_cargo() {
    let delta = dependency_delta(LockfileKind::Cargo, CARGO_BEFORE, CARGO_AFTER).unwrap();
    let added: Vec<_> = delta
        .added
        .iter()
        .map(|package| (package.name.as_str(), package.version.as_str()))
        .collect();
    let removed: Vec<_> = delta
        .removed
        .iter()
        .map(|package| (package.name.as_str(), package.version.as_str()))
        .collect();

    assert_eq!(added, vec![("badcrate", "2.0.0"), ("safecrate", "1.1.0")]);
    assert_eq!(removed, vec![("safecrate", "1.0.0")]);
    assert!(delta.added.iter().all(|package| package.ecosystem == Ecosystem::Cargo));
    assert_eq!(delta, dependency_delta(LockfileKind::Cargo, CARGO_BEFORE, CARGO_AFTER).unwrap());
}

#[test]
fn npm_lock_v3_infers_scoped_and_unscoped_package_names_from_paths() {
    let delta = dependency_delta(LockfileKind::Npm, NPM_BEFORE, NPM_AFTER).unwrap();
    let added: Vec<_> = delta
        .added
        .iter()
        .map(|package| (package.name.as_str(), package.version.as_str()))
        .collect();
    assert_eq!(added, vec![("@scope/tool", "4.5.6"), ("badpkg", "1.2.3")]);
    assert!(delta.removed.is_empty());
}

#[test]
fn offline_advisory_fixture_matches_only_added_exact_versions() {
    let provider = OfflineAdvisoryProvider::from_fixture(OFFLINE_ADVISORIES).unwrap();
    let cargo = dependency_delta(LockfileKind::Cargo, CARGO_BEFORE, CARGO_AFTER).unwrap();
    let npm = dependency_delta(LockfileKind::Npm, NPM_BEFORE, NPM_AFTER).unwrap();

    let cargo_matches = provider.match_added(&cargo);
    assert_eq!(cargo_matches.len(), 1);
    assert_eq!(cargo_matches[0].advisory_id, "OSV-TEST-CARGO-001");
    assert_eq!(cargo_matches[0].package.name, "badcrate");

    let npm_matches = provider.match_added(&npm);
    assert_eq!(npm_matches.len(), 1);
    assert_eq!(npm_matches[0].advisory_id, "OSV-TEST-NPM-001");
    assert_eq!(npm_matches[0].package.name, "badpkg");
}

#[test]
fn malformed_unsupported_and_oversized_lockfiles_fail_closed() {
    assert!(matches!(
        parse_lockfile(LockfileKind::Cargo, b"version = 4\n"),
        Err(DependencyError::InvalidFormat(_))
    ));
    assert!(matches!(
        parse_lockfile(
            LockfileKind::Npm,
            br#"{"lockfileVersion":1,"packages":{}}"#
        ),
        Err(DependencyError::InvalidFormat(_))
    ));
    assert!(matches!(
        parse_lockfile(LockfileKind::Cargo, &[0xff]),
        Err(DependencyError::NonUtf8)
    ));
    assert!(matches!(
        parse_lockfile(LockfileKind::Cargo, &vec![b'x'; MAX_LOCKFILE_BYTES + 1]),
        Err(DependencyError::InputTooLarge { .. })
    ));
}

#[test]
fn malformed_offline_advisory_data_fails_closed() {
    assert!(matches!(
        OfflineAdvisoryProvider::from_fixture(
            br#"{"schema_version":"1","advisories":[{"id":"X","ecosystem":"unknown","package":"p","affected_versions":["1"],"summary":"s"}]}"#
        ),
        Err(DependencyError::InvalidField("ecosystem"))
    ));
}
